[build]
rustflags = ["-C", "target-cpu=native", "-Z", "share-generics=y"]

# Use the mold linker
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[unstable]
sparse-registry = true
